export enum MenuPermission {
    ASSET = "AST",
    ASSETSTATUS = "AS",
    STATUSTRANSACTION = "ST",
    ASSETTYPE = "AT",
    BRAND = "BR",
    LOCATION = "LC",
    COMPANY = "CM",
    EMPLOYEE = "EMP",
    INVOICE = 'IC',
    USER = "USR",
    ROLE = "RL",
    PERMISSION = "PR",
    PERMISSIONDETAIL = "PD",
    CHECKOUT = "CO",
    CHECKIN = "CI", 
    TRANSACTION = "TR",
    TRACKASSET = "TA",
    ASSETLICENCEEXPIRED = "ALE",
    TRANSACTIONEXPIRED = "TE",
    INVENTORY = "INV"
  }